# Generated by Django 3.0.2 on 2020-03-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_auto_20200313_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_of_creation',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateField(null=True),
        ),
    ]
