# Generated by Django 3.0.2 on 2020-03-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20200316_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
