# Generated by Django 3.0.2 on 2020-03-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_auto_20200316_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(blank=True, related_name='tags', to='task_manager.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='task_manager.Tag'),
        ),
    ]
